In [221]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import pytz

In [222]:
sales = pd.read_csv("Sales-products-tz-mod.csv")
sales.head()

,SaleID,RetailerCountry,RetailerType,Product,Sales Revenue ($),DateOfSale,TimeOfSale,TimeZone
0,SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,200.0,06/01/2020,23:20:56,EST
1,SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,7.0,05/02/2020,17:27:08,EST
2,SaleID_3,United States,Outdoors Shop,Star Dome,20.0,30/10/2020,09:04:43,EST
3,SaleID_4,United States,Outdoors Shop,Star Gazer 2,40.0,13/11/2020,04:25:06,EST
4,SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,150.5,06/12/2020,11:15:47,CET

In [223]:
modified_sales = sales.copy()
modified_sales["date"] = modified_sales["DateOfSale"]+" "+modified_sales["TimeOfSale"]
modified_sales["date"] = pd.to_datetime(modified_sales["date"],format="%d/%m/%Y %H:%M:%S")
modified_sales.head()

,SaleID,RetailerCountry,RetailerType,Product,Sales Revenue ($),DateOfSale,TimeOfSale,TimeZone,date
0,SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,200.0,06/01/2020,23:20:56,EST,2020-01-06 23:20:56
1,SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,7.0,05/02/2020,17:27:08,EST,2020-02-05 17:27:08
2,SaleID_3,United States,Outdoors Shop,Star Dome,20.0,30/10/2020,09:04:43,EST,2020-10-30 09:04:43
3,SaleID_4,United States,Outdoors Shop,Star Gazer 2,40.0,13/11/2020,04:25:06,EST,2020-11-13 04:25:06
4,SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,150.5,06/12/2020,11:15:47,CET,2020-12-06 11:15:47

Here I find the unique values and find SGT as a timezone. Tha corresponds to Singapore. Since it was not in the pytz correct timezones, I modified that value to Singapore

In [224]:
pytz.all_timezones

['Africa/Abidjan',
 'Africa/Accra',
 'Africa/Addis_Ababa',
 'Africa/Algiers',
 'Africa/Asmara',
 'Africa/Asmera',
 'Africa/Bamako',
 'Africa/Bangui',
 'Africa/Banjul',
 'Africa/Bissau',
 'Africa/Blantyre',
 'Africa/Brazzaville',
 'Africa/Bujumbura',
 'Africa/Cairo',
 'Africa/Casablanca',
 'Africa/Ceuta',
 'Africa/Conakry',
 'Africa/Dakar',
 'Africa/Dar_es_Salaam',
 'Africa/Djibouti',
 'Africa/Douala',
 'Africa/El_Aaiun',
 'Africa/Freetown',
 'Africa/Gaborone',
 'Africa/Harare',
 'Africa/Johannesburg',
 'Africa/Juba',
 'Africa/Kampala',
 'Africa/Khartoum',
 'Africa/Kigali',
 'Africa/Kinshasa',
 'Africa/Lagos',
 'Africa/Libreville',
 'Africa/Lome',
 'Africa/Luanda',
 'Africa/Lubumbashi',
 'Africa/Lusaka',
 'Africa/Malabo',
 'Africa/Maputo',
 'Africa/Maseru',
 'Africa/Mbabane',
 'Africa/Mogadishu',
 'Africa/Monrovia',
 'Africa/Nairobi',
 'Africa/Ndjamena',
 'Africa/Niamey',
 'Africa/Nouakchott',
 'Africa/Ouagadougou',
 'Africa/Porto-Novo',
 'Africa/Sao_Tome',
 'Africa/Timbuktu',
 'Africa/Tripoli',
 'Africa/Tunis',
 'Africa/Windhoek',
 'America/Adak',
 'America/Anchorage',
 'America/Anguilla',
 'America/Antigua',
 'America/Araguaina',
 'America/Argentina/Buenos_Aires',
 'America/Argentina/Catamarca',
 'America/Argentina/ComodRivadavia',
 'America/Argentina/Cordoba',
 'America/Argentina/Jujuy',
 'America/Argentina/La_Rioja',
 'America/Argentina/Mendoza',
 'America/Argentina/Rio_Gallegos',
 'America/Argentina/Salta',
 'America/Argentina/San_Juan',
 'America/Argentina/San_Luis',
 'America/Argentina/Tucuman',
 'America/Argentina/Ushuaia',
 'America/Aruba',
 'America/Asuncion',
 'America/Atikokan',
 'America/Atka',
 'America/Bahia',
 'America/Bahia_Banderas',
 'America/Barbados',
 'America/Belem',
 'America/Belize',
 'America/Blanc-Sablon',
 'America/Boa_Vista',
 'America/Bogota',
 'America/Boise',
 'America/Buenos_Aires',
 'America/Cambridge_Bay',
 'America/Campo_Grande',
 'America/Cancun',
 'America/Caracas',
 'America/Catamarca',
 'America/Cayenne',
 'America/Cayman',
 'America/Chicago',
 'America/Chihuahua',
 'America/Ciudad_Juarez',
 'America/Coral_Harbour',
 'America/Cordoba',
 'America/Costa_Rica',
 'America/Creston',
 'America/Cuiaba',
 'America/Curacao',
 'America/Danmarkshavn',
 'America/Dawson',
 'America/Dawson_Creek',
 'America/Denver',
 'America/Detroit',
 'America/Dominica',
 'America/Edmonton',
 'America/Eirunepe',
 'America/El_Salvador',
 'America/Ensenada',
 'America/Fort_Nelson',
 'America/Fort_Wayne',
 'America/Fortaleza',
 'America/Glace_Bay',
 'America/Godthab',
 'America/Goose_Bay',
 'America/Grand_Turk',
 'America/Grenada',
 'America/Guadeloupe',
 'America/Guatemala',
 'America/Guayaquil',
 'America/Guyana',
 'America/Halifax',
 'America/Havana',
 'America/Hermosillo',
 'America/Indiana/Indianapolis',
 'America/Indiana/Knox',
 'America/Indiana/Marengo',
 'America/Indiana/Petersburg',
 'America/Indiana/Tell_City',
 'America/Indiana/Vevay',
 'America/Indiana/Vincennes',
 'America/Indiana/Winamac',
 'America/Indianapolis',
 'America/Inuvik',
 'America/Iqaluit',
 'America/Jamaica',
 'America/Jujuy',
 'America/Juneau',
 'America/Kentucky/Louisville',
 'America/Kentucky/Monticello',
 'America/Knox_IN',
 'America/Kralendijk',
 'America/La_Paz',
 'America/Lima',
 'America/Los_Angeles',
 'America/Louisville',
 'America/Lower_Princes',
 'America/Maceio',
 'America/Managua',
 'America/Manaus',
 'America/Marigot',
 'America/Martinique',
 'America/Matamoros',
 'America/Mazatlan',
 'America/Mendoza',
 'America/Menominee',
 'America/Merida',
 'America/Metlakatla',
 'America/Mexico_City',
 'America/Miquelon',
 'America/Moncton',
 'America/Monterrey',
 'America/Montevideo',
 'America/Montreal',
 'America/Montserrat',
 'America/Nassau',
 'America/New_York',
 'America/Nipigon',
 'America/Nome',
 'America/Noronha',
 'America/North_Dakota/Beulah',
 'America/North_Dakota/Center',
 'America/North_Dakota/New_Salem',
 'America/Nuuk',
 'America/Ojinaga',
 'America/Panama',
 'America/Pangnirtung',
 'America/Paramaribo',
 'America/Phoenix',
 'America/Port-au-Prince',
 'America/Port_of_Spain',
 'America/Porto_Acre',
 'America/Porto_Velho',
 'America/Puerto_Rico',
 'America/Punta_Arenas',
 'America/Rainy_River',
 'America/Rankin_Inlet',
 'America/Recife',
 'America/Regina',
 'America/Resolute',
 'America/Rio_Branco',
 'America/Rosario',
 'America/Santa_Isabel',
 'America/Santarem',
 'America/Santiago',
 'America/Santo_Domingo',
 'America/Sao_Paulo',
 'America/Scoresbysund',
 'America/Shiprock',
 'America/Sitka',
 'America/St_Barthelemy',
 'America/St_Johns',
 'America/St_Kitts',
 'America/St_Lucia',
 'America/St_Thomas',
 'America/St_Vincent',
 'America/Swift_Current',
 'America/Tegucigalpa',
 'America/Thule',
 'America/Thunder_Bay',
 'America/Tijuana',
 'America/Toronto',
 'America/Tortola',
 'America/Vancouver',
 'America/Virgin',
 'America/Whitehorse',
 'America/Winnipeg',
 'America/Yakutat',
 'America/Yellowknife',
 'Antarctica/Casey',
 'Antarctica/Davis',
 'Antarctica/DumontDUrville',
 'Antarctica/Macquarie',
 'Antarctica/Mawson',
 'Antarctica/McMurdo',
 'Antarctica/Palmer',
 'Antarctica/Rothera',
 'Antarctica/South_Pole',
 'Antarctica/Syowa',
 'Antarctica/Troll',
 'Antarctica/Vostok',
 'Arctic/Longyearbyen',
 'Asia/Aden',
 'Asia/Almaty',
 'Asia/Amman',
 'Asia/Anadyr',
 'Asia/Aqtau',
 'Asia/Aqtobe',
 'Asia/Ashgabat',
 'Asia/Ashkhabad',
 'Asia/Atyrau',
 'Asia/Baghdad',
 'Asia/Bahrain',
 'Asia/Baku',
 'Asia/Bangkok',
 'Asia/Barnaul',
 'Asia/Beirut',
 'Asia/Bishkek',
 'Asia/Brunei',
 'Asia/Calcutta',
 'Asia/Chita',
 'Asia/Choibalsan',
 'Asia/Chongqing',
 'Asia/Chungking',
 'Asia/Colombo',
 'Asia/Dacca',
 'Asia/Damascus',
 'Asia/Dhaka',
 'Asia/Dili',
 'Asia/Dubai',
 'Asia/Dushanbe',
 'Asia/Famagusta',
 'Asia/Gaza',
 'Asia/Harbin',
 'Asia/Hebron',
 'Asia/Ho_Chi_Minh',
 'Asia/Hong_Kong',
 'Asia/Hovd',
 'Asia/Irkutsk',
 'Asia/Istanbul',
 'Asia/Jakarta',
 'Asia/Jayapura',
 'Asia/Jerusalem',
 'Asia/Kabul',
 'Asia/Kamchatka',
 'Asia/Karachi',
 'Asia/Kashgar',
 'Asia/Kathmandu',
 'Asia/Katmandu',
 'Asia/Khandyga',
 'Asia/Kolkata',
 'Asia/Krasnoyarsk',
 'Asia/Kuala_Lumpur',
 'Asia/Kuching',
 'Asia/Kuwait',
 'Asia/Macao',
 'Asia/Macau',
 'Asia/Magadan',
 'Asia/Makassar',
 'Asia/Manila',
 'Asia/Muscat',
 'Asia/Nicosia',
 'Asia/Novokuznetsk',
 'Asia/Novosibirsk',
 'Asia/Omsk',
 'Asia/Oral',
 'Asia/Phnom_Penh',
 'Asia/Pontianak',
 'Asia/Pyongyang',
 'Asia/Qatar',
 'Asia/Qostanay',
 'Asia/Qyzylorda',
 'Asia/Rangoon',
 'Asia/Riyadh',
 'Asia/Saigon',
 'Asia/Sakhalin',
 'Asia/Samarkand',
 'Asia/Seoul',
 'Asia/Shanghai',
 'Asia/Singapore',
 'Asia/Srednekolymsk',
 'Asia/Taipei',
 'Asia/Tashkent',
 'Asia/Tbilisi',
 'Asia/Tehran',
 'Asia/Tel_Aviv',
 'Asia/Thimbu',
 'Asia/Thimphu',
 'Asia/Tokyo',
 'Asia/Tomsk',
 'Asia/Ujung_Pandang',
 'Asia/Ulaanbaatar',
 'Asia/Ulan_Bator',
 'Asia/Urumqi',
 'Asia/Ust-Nera',
 'Asia/Vientiane',
 'Asia/Vladivostok',
 'Asia/Yakutsk',
 'Asia/Yangon',
 'Asia/Yekaterinburg',
 'Asia/Yerevan',
 'Atlantic/Azores',
 'Atlantic/Bermuda',
 'Atlantic/Canary',
 'Atlantic/Cape_Verde',
 'Atlantic/Faeroe',
 'Atlantic/Faroe',
 'Atlantic/Jan_Mayen',
 'Atlantic/Madeira',
 'Atlantic/Reykjavik',
 'Atlantic/South_Georgia',
 'Atlantic/St_Helena',
 'Atlantic/Stanley',
 'Australia/ACT',
 'Australia/Adelaide',
 'Australia/Brisbane',
 'Australia/Broken_Hill',
 'Australia/Canberra',
 'Australia/Currie',
 'Australia/Darwin',
 'Australia/Eucla',
 'Australia/Hobart',
 'Australia/LHI',
 'Australia/Lindeman',
 'Australia/Lord_Howe',
 'Australia/Melbourne',
 'Australia/NSW',
 'Australia/North',
 'Australia/Perth',
 'Australia/Queensland',
 'Australia/South',
 'Australia/Sydney',
 'Australia/Tasmania',
 'Australia/Victoria',
 'Australia/West',
 'Australia/Yancowinna',
 'Brazil/Acre',
 'Brazil/DeNoronha',
 'Brazil/East',
 'Brazil/West',
 'CET',
 'CST6CDT',
 'Canada/Atlantic',
 'Canada/Central',
 'Canada/Eastern',
 'Canada/Mountain',
 'Canada/Newfoundland',
 'Canada/Pacific',
 'Canada/Saskatchewan',
 'Canada/Yukon',
 'Chile/Continental',
 'Chile/EasterIsland',
 'Cuba',
 'EET',
 'EST',
 'EST5EDT',
 'Egypt',
 'Eire',
 'Etc/GMT',
 'Etc/GMT+0',
 'Etc/GMT+1',
 'Etc/GMT+10',
 'Etc/GMT+11',
 'Etc/GMT+12',
 'Etc/GMT+2',
 'Etc/GMT+3',
 'Etc/GMT+4',
 'Etc/GMT+5',
 'Etc/GMT+6',
 'Etc/GMT+7',
 'Etc/GMT+8',
 'Etc/GMT+9',
 'Etc/GMT-0',
 'Etc/GMT-1',
 'Etc/GMT-10',
 'Etc/GMT-11',
 'Etc/GMT-12',
 'Etc/GMT-13',
 'Etc/GMT-14',
 'Etc/GMT-2',
 'Etc/GMT-3',
 'Etc/GMT-4',
 'Etc/GMT-5',
 'Etc/GMT-6',
 'Etc/GMT-7',
 'Etc/GMT-8',
 'Etc/GMT-9',
 'Etc/GMT0',
 'Etc/Greenwich',
 'Etc/UCT',
 'Etc/UTC',
 'Etc/Universal',
 'Etc/Zulu',
 'Europe/Amsterdam',
 'Europe/Andorra',
 'Europe/Astrakhan',
 'Europe/Athens',
 'Europe/Belfast',
 'Europe/Belgrade',
 'Europe/Berlin',
 'Europe/Bratislava',
 'Europe/Brussels',
 'Europe/Bucharest',
 'Europe/Budapest',
 'Europe/Busingen',
 'Europe/Chisinau',
 'Europe/Copenhagen',
 'Europe/Dublin',
 'Europe/Gibraltar',
 'Europe/Guernsey',
 'Europe/Helsinki',
 'Europe/Isle_of_Man',
 'Europe/Istanbul',
 'Europe/Jersey',
 'Europe/Kaliningrad',
 'Europe/Kiev',
 'Europe/Kirov',
 'Europe/Kyiv',
 'Europe/Lisbon',
 'Europe/Ljubljana',
 'Europe/London',
 'Europe/Luxembourg',
 'Europe/Madrid',
 'Europe/Malta',
 'Europe/Mariehamn',
 'Europe/Minsk',
 'Europe/Monaco',
 'Europe/Moscow',
 'Europe/Nicosia',
 'Europe/Oslo',
 'Europe/Paris',
 'Europe/Podgorica',
 'Europe/Prague',
 'Europe/Riga',
 'Europe/Rome',
 'Europe/Samara',
 'Europe/San_Marino',
 'Europe/Sarajevo',
 'Europe/Saratov',
 'Europe/Simferopol',
 'Europe/Skopje',
 'Europe/Sofia',
 'Europe/Stockholm',
 'Europe/Tallinn',
 'Europe/Tirane',
 'Europe/Tiraspol',
 'Europe/Ulyanovsk',
 'Europe/Uzhgorod',
 'Europe/Vaduz',
 'Europe/Vatican',
 'Europe/Vienna',
 'Europe/Vilnius',
 'Europe/Volgograd',
 'Europe/Warsaw',
 'Europe/Zagreb',
 'Europe/Zaporozhye',
 'Europe/Zurich',
 'GB',
 'GB-Eire',
 'GMT',
 'GMT+0',
 'GMT-0',
 'GMT0',
 'Greenwich',
 'HST',
 'Hongkong',
 'Iceland',
 'Indian/Antananarivo',
 'Indian/Chagos',
 'Indian/Christmas',
 'Indian/Cocos',
 'Indian/Comoro',
 'Indian/Kerguelen',
 'Indian/Mahe',
 'Indian/Maldives',
 'Indian/Mauritius',
 'Indian/Mayotte',
 'Indian/Reunion',
 'Iran',
 'Israel',
 'Jamaica',
 'Japan',
 'Kwajalein',
 'Libya',
 'MET',
 'MST',
 'MST7MDT',
 'Mexico/BajaNorte',
 'Mexico/BajaSur',
 'Mexico/General',
 'NZ',
 'NZ-CHAT',
 'Navajo',
 'PRC',
 'PST8PDT',
 'Pacific/Apia',
 'Pacific/Auckland',
 'Pacific/Bougainville',
 'Pacific/Chatham',
 'Pacific/Chuuk',
 'Pacific/Easter',
 'Pacific/Efate',
 'Pacific/Enderbury',
 'Pacific/Fakaofo',
 'Pacific/Fiji',
 'Pacific/Funafuti',
 'Pacific/Galapagos',
 'Pacific/Gambier',
 'Pacific/Guadalcanal',
 'Pacific/Guam',
 'Pacific/Honolulu',
 'Pacific/Johnston',
 'Pacific/Kanton',
 'Pacific/Kiritimati',
 'Pacific/Kosrae',
 'Pacific/Kwajalein',
 'Pacific/Majuro',
 'Pacific/Marquesas',
 'Pacific/Midway',
 'Pacific/Nauru',
 'Pacific/Niue',
 'Pacific/Norfolk',
 'Pacific/Noumea',
 'Pacific/Pago_Pago',
 'Pacific/Palau',
 'Pacific/Pitcairn',
 'Pacific/Pohnpei',
 'Pacific/Ponape',
 'Pacific/Port_Moresby',
 'Pacific/Rarotonga',
 'Pacific/Saipan',
 'Pacific/Samoa',
 'Pacific/Tahiti',
 'Pacific/Tarawa',
 'Pacific/Tongatapu',
 'Pacific/Truk',
 'Pacific/Wake',
 'Pacific/Wallis',
 'Pacific/Yap',
 'Poland',
 'Portugal',
 'ROC',
 'ROK',
 'Singapore',
 'Turkey',
 'UCT',
 'US/Alaska',
 'US/Aleutian',
 'US/Arizona',
 'US/Central',
 'US/East-Indiana',
 'US/Eastern',
 'US/Hawaii',
 'US/Indiana-Starke',
 'US/Michigan',
 'US/Mountain',
 'US/Pacific',
 'US/Samoa',
 'UTC',
 'Universal',
 'W-SU',
 'WET',
 'Zulu']

In [225]:
modified_sales["TimeZone"].unique()

array(['EST', 'CET', 'GMT', 'EET', 'SGT', 'Australia/West'], dtype=object)

In [249]:
modified_sales.loc[modified_sales["TimeZone"]=="SGT","TimeZone"] = "Singapore"

In [250]:
modified_sales.head(19)

,SaleID,RetailerCountry,RetailerType,Product,Sales Revenue ($),DateOfSale,TimeOfSale,TimeZone,date
0,SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,200.00,06/01/2020,23:20:56,EST,2020-01-06 23:20:56
1,SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,7.00,05/02/2020,17:27:08,EST,2020-02-05 17:27:08
2,SaleID_3,United States,Outdoors Shop,Star Dome,20.00,30/10/2020,09:04:43,EST,2020-10-30 09:04:43
3,SaleID_4,United States,Outdoors Shop,Star Gazer 2,40.00,13/11/2020,04:25:06,EST,2020-11-13 04:25:06
4,SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,150.50,06/12/2020,11:15:47,CET,2020-12-06 11:15:47
5,SaleID_6,Italy,Outdoors Shop,Firefly 4,1300.00,07/06/2020,01:54:41,CET,2020-06-07 01:54:41
6,SaleID_7,United Kingdom,Outdoors Shop,Husky Rope 50,270.00,27/12/2020,02:07:28,GMT,2020-12-27 02:07:28
7,SaleID_8,United Kingdom,Outdoors Shop,Granite Signal Mirror,499.99,15/09/2020,11:44:57,GMT,2020-09-15 11:44:57
8,SaleID_9,United Kingdom,Outdoors Shop,Granite Carabiner,32.00,23/09/2020,01:40:29,GMT,2020-09-23 01:40:29
9,SaleID_10,Italy,Outdoors Shop,Granite Grip,220.00,24/06/2020,18:43:04,CET,2020-06-24 18:43:04
10,SaleID_11,Italy,Outdoors Shop,Granite Axe,49.99,19/05/2019,02:12:30,CET,2019-05-19 02:12:30
11,SaleID_12,Mexico,Mall,Ranger Vision,350.00,05/04/2019,07:38:10,EST,2019-04-05 07:38:10
12,SaleID_13,Mexico,Mall,Trail Scout,80.00,24/01/2020,08:51:28,EST,2020-01-24 08:51:28
13,SaleID_14,Mexico,Mall,Hailstorm Steel Irons,240.00,07/12/2019,08:14:53,EST,2019-12-07 08:14:53
14,SaleID_15,Mexico,Mall,Course Pro Umbrella,100.32,13/01/2020,05:32:40,EST,2020-01-13 05:32:40
15,SaleID_16,Mexico,Mall,Course Pro Golf Bag,620.00,26/11/2020,10:17:48,EET,2020-11-26 10:17:48
16,SaleID_17,Mexico,Mall,Course Pro Gloves,40.50,23/01/2020,19:36:25,EET,2020-01-23 19:36:25
17,SaleID_18,Singapore,Outdoors Shop,Granite Pulley,19.00,02/01/2019,01:32:09,Singapore,2019-01-02 01:32:09
18,SaleID_19,Singapore,Outdoors Shop,Firefly Climbing Lamp,23.45,20/02/2019,07:07:10,Singapore,2019-02-20 07:07:10

Create a function to put the timezone

In [251]:
def assign_timezone(row):
  date = pd.to_datetime(row["date"])
  print(row["SaleID"])
  return date.tz_localize(row["TimeZone"])

In [252]:
modified_sales["date"] = modified_sales.apply(assign_timezone,axis=1)

SaleID_1
SaleID_2
SaleID_3
SaleID_4
SaleID_5
SaleID_6
SaleID_7
SaleID_8
SaleID_9
SaleID_10
SaleID_11
SaleID_12
SaleID_13
SaleID_14
SaleID_15
SaleID_16
SaleID_17
SaleID_18
SaleID_19
SaleID_20
SaleID_21
SaleID_22
SaleID_23
SaleID_24
SaleID_25
SaleID_26
SaleID_27
SaleID_28
SaleID_29
SaleID_30
SaleID_31
SaleID_32
SaleID_33
SaleID_34
SaleID_35
SaleID_36
SaleID_37
SaleID_38
SaleID_39
SaleID_40
SaleID_41
SaleID_42
SaleID_43
SaleID_44
SaleID_45
SaleID_46
SaleID_47
SaleID_48
SaleID_49
SaleID_50
SaleID_51
SaleID_52
SaleID_53
SaleID_54
SaleID_55
SaleID_56
SaleID_57
SaleID_58
SaleID_59
SaleID_60
SaleID_61
SaleID_62
SaleID_63
SaleID_64
SaleID_65
SaleID_66
SaleID_67
SaleID_68
SaleID_69
SaleID_70
SaleID_71
SaleID_72
SaleID_73
SaleID_74
SaleID_75
SaleID_76
SaleID_77
SaleID_78
SaleID_79
SaleID_80
SaleID_81
SaleID_82
SaleID_83
SaleID_84
SaleID_85
SaleID_86
SaleID_87
SaleID_88
SaleID_89
SaleID_90
SaleID_91
SaleID_92
SaleID_93
SaleID_94
SaleID_95
SaleID_96
SaleID_97
SaleID_98
SaleID_99
SaleID_100

In [254]:
modified_sales.head(20)

,SaleID,RetailerCountry,RetailerType,Product,Sales Revenue ($),DateOfSale,TimeOfSale,TimeZone,date
0,SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,200.00,06/01/2020,23:20:56,EST,2020-01-06 23:20:56-05:00
1,SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,7.00,05/02/2020,17:27:08,EST,2020-02-05 17:27:08-05:00
2,SaleID_3,United States,Outdoors Shop,Star Dome,20.00,30/10/2020,09:04:43,EST,2020-10-30 09:04:43-05:00
3,SaleID_4,United States,Outdoors Shop,Star Gazer 2,40.00,13/11/2020,04:25:06,EST,2020-11-13 04:25:06-05:00
4,SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,150.50,06/12/2020,11:15:47,CET,2020-12-06 11:15:47+01:00
5,SaleID_6,Italy,Outdoors Shop,Firefly 4,1300.00,07/06/2020,01:54:41,CET,2020-06-07 01:54:41+02:00
6,SaleID_7,United Kingdom,Outdoors Shop,Husky Rope 50,270.00,27/12/2020,02:07:28,GMT,2020-12-27 02:07:28+00:00
7,SaleID_8,United Kingdom,Outdoors Shop,Granite Signal Mirror,499.99,15/09/2020,11:44:57,GMT,2020-09-15 11:44:57+00:00
8,SaleID_9,United Kingdom,Outdoors Shop,Granite Carabiner,32.00,23/09/2020,01:40:29,GMT,2020-09-23 01:40:29+00:00
9,SaleID_10,Italy,Outdoors Shop,Granite Grip,220.00,24/06/2020,18:43:04,CET,2020-06-24 18:43:04+02:00
10,SaleID_11,Italy,Outdoors Shop,Granite Axe,49.99,19/05/2019,02:12:30,CET,2019-05-19 02:12:30+02:00
11,SaleID_12,Mexico,Mall,Ranger Vision,350.00,05/04/2019,07:38:10,EST,2019-04-05 07:38:10-05:00
12,SaleID_13,Mexico,Mall,Trail Scout,80.00,24/01/2020,08:51:28,EST,2020-01-24 08:51:28-05:00
13,SaleID_14,Mexico,Mall,Hailstorm Steel Irons,240.00,07/12/2019,08:14:53,EST,2019-12-07 08:14:53-05:00
14,SaleID_15,Mexico,Mall,Course Pro Umbrella,100.32,13/01/2020,05:32:40,EST,2020-01-13 05:32:40-05:00
15,SaleID_16,Mexico,Mall,Course Pro Golf Bag,620.00,26/11/2020,10:17:48,EET,2020-11-26 10:17:48+02:00
16,SaleID_17,Mexico,Mall,Course Pro Gloves,40.50,23/01/2020,19:36:25,EET,2020-01-23 19:36:25+02:00
17,SaleID_18,Singapore,Outdoors Shop,Granite Pulley,19.00,02/01/2019,01:32:09,Singapore,2019-01-02 01:32:09+08:00
18,SaleID_19,Singapore,Outdoors Shop,Firefly Climbing Lamp,23.45,20/02/2019,07:07:10,Singapore,2019-02-20 07:07:10+08:00
19,SaleID_20,Singapore,Outdoors Shop,Granite Ice,65.00,10/04/2019,10:27:26,Singapore,2019-04-10 10:27:26+08:00

In [269]:
sorted_df = modified_sales.copy()
sorted_df["date"] = pd.to_datetime(sorted_df["date"],format="%Y/%m/%d %H:%M:%S%z",utc=True)

In [270]:
sorted_df

,SaleID,RetailerCountry,RetailerType,Product,Sales Revenue ($),DateOfSale,TimeOfSale,TimeZone,date
0,SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,200.0,06/01/2020,23:20:56,EST,2020-01-07 04:20:56+00:00
1,SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,7.0,05/02/2020,17:27:08,EST,2020-02-05 22:27:08+00:00
2,SaleID_3,United States,Outdoors Shop,Star Dome,20.0,30/10/2020,09:04:43,EST,2020-10-30 14:04:43+00:00
3,SaleID_4,United States,Outdoors Shop,Star Gazer 2,40.0,13/11/2020,04:25:06,EST,2020-11-13 09:25:06+00:00
4,SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,150.5,06/12/2020,11:15:47,CET,2020-12-06 10:15:47+00:00
...,...,...,...,...,...,...,...,...,...
95,SaleID_96,Australia,Sports Store,Mountain Man Extreme,24.0,23/07/2019,12:30:03,Australia/West,2019-07-23 04:30:03+00:00
96,SaleID_97,Australia,Department Store,Firefly Mapreader,1200.0,03/01/2019,01:39:14,Australia/West,2019-01-02 17:39:14+00:00
97,SaleID_98,Australia,Discount Retailer,Polar Sun,32.0,14/02/2019,21:29:35,Australia/West,2019-02-14 13:29:35+00:00
98,SaleID_99,Australia,Discount Retailer,Polar Ice,18.0,19/06/2020,11:16:19,Australia/West,2020-06-19 03:16:19+00:00
99,SaleID_100,Australia,Discount Retailer,Polar Sports,85.0,25/05/2019,15:51:41,Australia/West,2019-05-25 07:51:41+00:00

In [271]:
sorted_df.sort_values("date")

,SaleID,RetailerCountry,RetailerType,Product,Sales Revenue ($),DateOfSale,TimeOfSale,TimeZone,date
17,SaleID_18,Singapore,Outdoors Shop,Granite Pulley,19.00,02/01/2019,01:32:09,Singapore,2019-01-01 17:32:09+00:00
96,SaleID_97,Australia,Department Store,Firefly Mapreader,1200.00,03/01/2019,01:39:14,Australia/West,2019-01-02 17:39:14+00:00
52,SaleID_53,Canada,Sports Store,Opera Vision,450.00,03/01/2019,15:40:25,EST,2019-01-03 20:40:25+00:00
54,SaleID_55,Canada,Sports Store,Glacier Basic,140.00,10/01/2019,19:37:17,EST,2019-01-11 00:37:17+00:00
36,SaleID_37,Canada,Outdoors Shop,Capri,35.00,11/01/2019,14:24:52,EST,2019-01-11 19:24:52+00:00
...,...,...,...,...,...,...,...,...,...
31,SaleID_32,United Kingdom,Online Retailer,Granite Grip,220.00,08/12/2020,07:43:15,GMT,2020-12-08 07:43:15+00:00
84,SaleID_85,Australia,Outdoors Shop,Polar Sun,16.99,08/12/2020,23:39:32,Australia/West,2020-12-08 15:39:32+00:00
34,SaleID_35,Canada,Outdoors Shop,Legend,641.00,20/12/2020,20:25:08,EST,2020-12-21 01:25:08+00:00
6,SaleID_7,United Kingdom,Outdoors Shop,Husky Rope 50,270.00,27/12/2020,02:07:28,GMT,2020-12-27 02:07:28+00:00
37,SaleID_38,Canada,Mall,Trail Master,1300.00,31/12/2020,21:14:38,EST,2021-01-01 02:14:38+00:00

In [278]:
sorted_df.groupby("TimeZone").mean("Sales Revenue ($)").sort_values("Sales Revenue ($)",ascending=False)

                Sales Revenue ($)
TimeZone
EET                    586.687500
CET                    415.710000
Australia/West         273.105882
EST                    230.385500
GMT                    115.137273
Singapore               27.688750